version: "4.4"

services:
  database: 
    image: postgres
    container_name: database_rentx
    restart: always
    ports: 
      - 5432:5432
    environment:
      - POSTGRES_USER=rentx_user
      - POSTGRES_PASSWORD=123456
      - POSTGRES_DB=rentx_db
    volumes:
      - pgdata:/data/postgres

volumes:
  pgdata:
    driver: local

networks:
  default:
    name: network_rentx
    driver: bridge